### ISSUE TITLE
Include MIT license file

### ISSUE THREAD

**Issue by hegjon** [leafo/loadkit#3]
I'm packaging lua-loadkit for Fedora Linux [1], we use tarball generated from the git tag, so it is enough to include the license file in git.

Both Fedora Linux and the MIT license requires that we include the license in software that we redistribute.

See https://docs.fedoraproject.org/en-US/packaging-guidelines/LicensingGuidelines/#_license_text for more details

[1] https://bugzilla.redhat.com/show_bug.cgi?id=2143028

**Comment by alerque** [comment]
Arch Linux requires this too. I see I overlooked it when packaging but it would be nice to correct.
